### ISSUE TITLE
How to use it? 

### ISSUE THREAD

**Issue by VanTuz5** [shigurekt/saucenao-sorting#1]
I can't figure out how to use this script in any way. I ran it, but instead of the result it showed me only errors. Api and path was moddifieded.
![image](https://user-images.githubusercontent.com/39066280/90193520-ccaac800-ddcd-11ea-82a7-124d37613f4d.png)

**Comment by shigurekt** [comment]
You need to open the script in a python reader, and add in your own filepath (where all the images are contained) and also your API code. The API can be obtained by registering for a SauceNAO account.

**Comment by VanTuz5** [comment]
I did so, but the program still does not work
